service: serverless-sandbox-php-custom-runtime

provider:
    name: aws
    region: eu-west-3

plugins:
    - ./vendor/bref/bref

functions:
    api:
        handler: index.php
        description: ''
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        runtime: provided.al2
        layers:
            - ${bref:layer.php-80-fpm}
        events:
            -   httpApi: '*'

# Exclude files from deployment
package:
    exclude:
        - 'node_modules/**'
        - 'tests/**'
